export type ComponentKind =
  | 'users' | 'cdn' | 'loadbalancer' | 'ratelimiter' | 'server'
  | 'cache' | 'database' | 'queue' | 'storage';

export interface NodeConfig {
  // users
  users?: number;                 // set by the global load slider on the users node
  // server
  instances?: number;             // horizontal scale, 1..10000
  rpsPerInstance?: number;
  // server — autoscaling (additive)
  autoscale?: 'off' | 'on';
  minInstances?: number;          // 1..10000
  maxInstances?: number;          // 1..10000
  targetUtilization?: number;     // fraction 0..1, default 0.7 — autoscaler's per-instance target
  // server — retries (additive)
  retriesEnabled?: 'off' | 'on';
  maxRetries?: number;            // 0..5
  // server — circuit breaker (additive)
  circuitBreaker?: 'off' | 'on';
  circuitThreshold?: number;      // fraction 0..1, default 0.9 — downstream util that trips the breaker
  // loadbalancer
  algorithm?: 'round-robin' | 'least-connections';
  // ratelimiter
  limitRps?: number;
  // cache / cdn
  hitRatio?: number;              // 0..1
  capacityRps?: number;           // additive — makes the cache/CDN capacity ceiling configurable
  // database
  readReplicas?: number;          // 0..15
  shards?: number;                // 1..64
  maxConnections?: number;        // additive — total connection pool size (Little's Law cap)
  // queue
  workers?: number;
  jobsPerWorkerRps?: number;
  mode?: 'queue' | 'pubsub';      // additive — pub/sub fan-out instead of load-split
  subscriberCount?: number;       // additive — 1..20, only meaningful in pubsub mode
}

export interface SimNode {
  id: string;
  kind: ComponentKind;
  label: string;
  config: NodeConfig;
}

export interface SimEdge { id: string; source: string; target: string; }

export interface GlobalConfig {
  users: number;                  // 10 .. 500_000_000 (log slider)
  rpsPerUser: number;             // default 0.1
  readWriteRatio: number;         // fraction of reads, default 0.9
}

export interface SimGraph { nodes: SimNode[]; edges: SimEdge[]; global: GlobalConfig; }

export type Health = 'idle' | 'ok' | 'warn' | 'hot' | 'overloaded' | 'down';

export interface NodeMetrics {
  nodeId: string;
  inRps: number;                  // offered load
  servedRps: number;
  droppedRps: number;             // errors due to overload
  shedRps: number;                // deliberately rejected (rate limiter) — not an error
  utilization: number;            // 0..∞ (>1 = overloaded)
  latencyMs: number;              // effective per-hop latency incl. queueing
  health: Health;
  costPerMonth: number;
  warnings: string[];             // e.g. "No downstream server connected"
  effectiveInstances?: number;    // additive — autoscaler's resolved instance count (server only)
  retriedRps?: number;            // additive — extra downstream demand generated by retry amplification
}

export interface EdgeMetrics {
  edgeId: string;
  rps: number;
  droppedShare: number;           // 0..1 fraction of this edge's traffic that will fail downstream
}

export interface SimResult {
  nodes: Record<string, NodeMetrics>;
  edges: Record<string, EdgeMetrics>;
  totals: {
    offeredRps: number;
    servedRps: number;
    availability: number;         // servedRps / (offered - shed), 0..1
    p50Ms: number;
    p99Ms: number;
    costPerMonth: number;
    verdict: 'healthy' | 'degraded' | 'meltdown';
    bottlenecks: string[];        // node ids sorted by utilization desc, util > 0.9
    graphWarnings: string[];      // structural problems
  };
}
